source "https://rubygems.org"

ruby "3.4.5"

gem "rails", "~> 8.0.0"
gem "pg", "~> 1.5"
gem "puma", ">= 6.0"
gem "bcrypt", "~> 3.1.7"
gem "jwt"
gem "rack-cors"
gem "active_model_serializers"
gem "http"
gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "bootsnap", require: false

# JIT and Performance Optimization
gem "redis", "~> 5.0"
gem "sidekiq", "~> 7.0"
gem "oj", "~> 3.16"
gem "memory_profiler"
gem "stackprof"
gem "rack-mini-profiler"

group :development, :test do
  gem "debug", platforms: %i[ mri windows ]
end

group :development do
  gem "error_highlight", ">= 0.4.0", platforms: [:ruby]
end

